{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        ports:
        - containerPort: {{ .service.port }}
        env:
        - name: AWS_LOG_GROUP
          value: "{{ $.Values.awsLogsGroup }}"
        - name: AWS_REGION
          value: "{{ $.Values.awsRegion }}"
{{- end }}
