{{- range $serviceName, $service := .Values.services }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-service
  labels:
    app: {{ $serviceName }}
spec:
  type: {{ $.Values.serviceType | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ $service.service.port | default 80 }}
      targetPort: {{ $service.service.port | default 80 }}
  selector:
    app: {{ $serviceName }}

{{- end }}

