{{- range $serviceName, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-service
  labels:
    app: {{ $serviceName }}
spec:
  type: {{ $.Values.serviceType | default "ClusterIP" }}  # 若 .service.type 為 nil，則使用預設值 "ClusterIP"
  ports:
  - protocol: TCP
    port: {{ $service.service.port }}  # 引用每個服務的 port
    targetPort: {{ $service.service.port }}  # 引用每個服務的 targetPort
  selector:
    app: {{ $serviceName }}  # 確保 selector 指向正確的服務
{{- end }}
