{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  labels:
    app: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}  # 若 .service.type 為 nil，則使用預設值 "ClusterIP"
  ports:
  - protocol: TCP
    port: {{ .service.port }}  # 引用每個服務的 port
    targetPort: {{ .service.port }}  # 引用每個服務的 targetPort
  selector:
    app: {{ .name }}  # 確保 selector 指向正確的服務
{{- end }}
