#確認 Service 與 Deployment 的 Selector 配對
#deployment.yaml 中的 .spec.selector.matchLabels 和 service.yaml 中的 .spec.selector 要完全匹配。確保 app 標籤在 Deployment 和 Service 中一致。

{{- range $serviceName, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}-deployment
  labels:
    app: {{ $serviceName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
        - name: {{ $serviceName }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          ports:
          - containerPort: {{ $service.service.port | default 80 }}
          env:
          - name: AWS_LOG_GROUP
            value: "{{ $.Values.awsLogsGroup }}"
          - name: AWS_REGION
            value: "{{ $.Values.awsRegion }}"
{{- end }}
