apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: my-app
spec:
  type: {{ .Values.service1.type }}
  ports:
    - port: {{ .Values.service1.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: my-app
