apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: my-app
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: my-app
